#!/bin/ksh
#This scrip checks the snapmirror relationship on clusters
#Initial version 0.1
#Author: Geri
#
#about the initial version:
#checks if a cluster has unhealthy or "-" snapmirror ("-" means the relationship is not in mirrored state, like Broken-off
#if yes, then checks what is the issue
#if the snapmirror is not updating, that means the sm cannot be updated, manual intervention is necessary
#if the snapmirror is updating then checks the lag time
#finally it sends a mail if there was anything wrong
#
#Version	0.2
#Date		2014/06/27
#A snapmirror's health could be in 3 different state: true, false, -
#	the - means the state is not snapmirrored
#	the initial version didn't check for it, it is updated now.

version="0.2"
WORKDIR=/santeam/temp
TMPFILE=$WORKDIR/clsmtmp
TMPFILE2=$WORKDIR/clsmtmp2
RESULT=$WORKDIR/clsmstatus
BAD=$WORKDIR/clsmbad
GNUdate=/usr/local/bin/date
initscript=/opt/CITCOSan/Drivers/Driver_init
MAILTO=sanadmin@citco.com

> $RESULT

if [[ "$CLUSTERS" == "" ]];then
	. $initscript
fi

#get the list of clusters
CheckClusters=`for i in $CLUSTERS;do echo $i|awk -F: '{print $1}';done`

for NetAppClu in $CheckClusters; do
	echo Working on $NetAppClu...
	#Query the snapmirror destination
	#atl0nc01://atl0vmsan01/pod153_tempdata DP $NetAppClu://mia0vmsan01/pod153_tempdata Snapmirrored Idle - false
	ssh $NetAppClu snapmirror show -hea false,- | dos2unix 2>/dev/null | egrep -v "^$NetAppClu" | egrep "DP|no entries matching your query" > $TMPFILE
	
	#in this case there is no issue
	SMSTATUS=`cat $TMPFILE | egrep "no entries matching your query"`
	#echo SM=$SMSTATUS FilerTimeInUnix=$FilerTimeInUnix Filer_DATE=$Filer_DATE
	if [[ "$SMSTATUS" == "" ]]; then
		#empty $volnames
		volumenames=""
		#get filer time, convert it to unix format
		Filer_DATE=`ssh $NetAppClu date  | grep : | head -1 | sed 's/ *\([^ ]* *\)$//'`
		FilerTimeInUnix=`$GNUdate --date="$Filer_DATE" +%s`

		#we check for the volumes that cannot be updated
		cat $TMPFILE | egrep "false$| - -$" > $BAD
		if [ -s $BAD ]; then
			echo "This snapmirror(s) cannot be updated:" | tee -a $RESULT
			cat $BAD | tee -a $RESULT
		fi
	

		#if SMSTATUS is zero that means there is something wrong on the dest, we need to check
		cat $TMPFILE | egrep -v " - false| - -$" | while myline=`line`;do
			volumenames="$volumenames,`echo $myline | awk '{print $3}' | awk -F/ '{print $4}'`"
		done
		volumenames=`echo $volumenames | sed 's/^,//' | sed 's/,$//'`
		#echo VOLNAMES=\"$volumenames\"
	
		if [[ "$volumenames" != "" ]];then
			#$NetAppClu://mia0vmsan01/pod102_oradata snapmirror.71cef530-6b45-11e2-8f42-123478563412_3_2147484855.2013-09-27_165106 09/27 16:51:06
			ssh $NetAppClu snapmirror show $volumenames -fields newest-snapshot-timestamp,newest-snapshot | dos2unix 2>/dev/null | grep $NetAppClu | sed 's/"//g' | awk '{print $2, $3, $4, $5}' | tee $TMPFILE2
			echo >> $RESULT
			echo "The following mirrors have lag issue in $NetAppClu cluster:" | tee -a $RESULT
			cat $TMPFILE2 | while myline=`line`;do
				echo $myline | read volname year month_day HMS
				volname=`echo $volname | awk -F/ '{print $4}'`
				year=`echo $year | awk -F. '{print $3}' | awk -F- '{print $1}'`
				sm_time=`$GNUdate --date="$month_day $HMS $year" +%s`
				Delta=`echo $FilerTimeInUnix-$sm_time|bc`
				echo Delta=$Delta
					#24h 86400
				#1h 3600 
				OutTXT="The volume $volname has snapmirror lag time that is"
				UTCDelta="1970-01-01 00:00:00 UTC + $Delta seconds"
				if [ $Delta -gt 86400 ];then
					$GNUdate -d "$UTCDelta" -u +%d:%H:%M:%S | awk -F: '{print $1, $2, $3, $4}' | read Days Hours Minutes Seconds
					Hours=`echo "($Days-1)*24+$Hours"|bc`
					echo "$OutTXT $Hours:$Minutes:$Seconds hours." | tee -a $RESULT
				else
					if [ $Delta -gt 3600 ];then
						PrintDelta=`$GNUdate -d "$UTCDelta" -u +%H:%M:%S`
						echo "$OutTXT $PrintDelta hours." | tee -a $RESULT
					else
						if [ $Delta -gt 1800 ];then
							PrintDelta=`$GNUdate -d "$UTCDelta" -u +%M:%S`
							echo "$OutTXT $PrintDelta minutes." | tee -a $RESULT
						fi
					fi
				fi
			done
		fi
	
		if [ -s $RESULT ];then
			echo "There were issues, sending alert mail."
			cat $RESULT
			cat $RESULT|mailx -r GCheck -s "Clustered OnTap SnapMirrorCheck" $MAILTO
		fi
	else
		echo "There were no issues in $NetAppClu"
	fi
done
